osx_image: xcode7.3

sudo: required
dist: trusty

language: c

env:
  - TEST_SUITE=tests

cache:
  directories:
  - node_modules
  - app/node_modules
  - app/jspm_packages
  - $HOME/.electron
  - $HOME/.cache

install:
  chmod a+x travis.sh


script:
  - ./travis.sh

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
