platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

environment:
  GH_TOKEN:
    secure: z50LX4xcOBFTM9jYOkOY/H2xA6u609DBszAgfARNwUhBOkvAaQqM+qkmXISCahH8

install:
  - ps: Install-Product node 4.4.7 x64
  - git reset --hard HEAD
  - npm install gulp npm@next jspm@0.16.39 flatten-packages windows-build-tools --production -g
  - npm install
  - npm prune
  - cd app
  - npm install
  - jspm install
  - flatten-packages
  - cd ..

build_script:
  - gulp build-release
  - gulp rename-index
  - npm run dist
  - gulp rename-index-back


test: off
